image: alpine:latest

variables:
  MODULE_NAME: "anvil-menu"

before_script:
  - apk update && apk add --no-cache zip jq

build-module:
  stage: build
  script:
  - echo "Updating $MODULE_NAME module.json"
  - mv $MODULE_NAME/module.json $MODULE_NAME/module.base.json
  - jq --arg manifest "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/module.json?job=build-module" --arg download "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/$MODULE_NAME.zip?job=build-module" '.manifest = $manifest | .download = $download' $MODULE_NAME/module.base.json > $MODULE_NAME/module.json
  - rm $MODULE_NAME/module.base.json
  - echo "Building $MODULE_NAME module ZIP file"
  - zip -r $MODULE_NAME.zip $MODULE_NAME
  artifacts:
    paths:
      - $MODULE_NAME.zip
      - module.json
  only:
    refs:
      - develop
      - master
