image: alpine:latest

before_script:
  - apk update && apk add --no-cache zip

zip-module:
  stage: build
  script:
  - echo 'Building module ZIP file'
  - zip -r anvil-menu.zip anvil-menu
  artifacts:
    paths:
    - anvil-menu.zip
