image: alpine:latest

variables:
  MODULE_NAME: "anvil-menu"

before_script:
  - apk update && apk add --no-cache zip jq

build-module:
  stage: build
  script:
  - echo "Building $MODULE_NAME module ZIP file"
  - zip -r "$MODULE_NAME.zip" "$MODULE_NAME"
  # https://gitlab.com/Ionshard/foundry-vtt-anvil-menu/-/jobs/artifacts/develop/download?job=zip-module
  - jq --arg manifest "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/module.json?job=build-module" --arg download "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_SLUG/raw/$MODULE_NAME.zip?job=build-module" '.manifest = $manifest | .download = $download' anvil-menu/module.json > module.json
  artifacts:
    paths:
      - $MODULE_NAME.zip
      - module.json
  only:
    refs:
      - develop
      - master
