image: alpine:latest

before_script:
  - apt update -qq && apt add -y -qq zip

make-zip:
  stage: build
  script:
  - echo 'Building module ZIP file'
  - zip -r anvil-menu.zip anvil-menu.zip
  artifacts:
    paths:
    - anvil-menu.zip
